[package]
name = "ds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["in-order"]
in-order = []
pre-order = []
post-order = []
test-rbt-snapshot = []

[dependencies]
rand = "^0.8"